import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Url Short</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex  text-2xl text-center">
        <h1>Url Shortner 🔗</h1>
        <p>Created using NextJS , Planetscale , Typescript !! 🔥</p>
      </div>
    </>
  );
};

export default Home;
